### ISSUE TITLE
Adding `tracing_opentelemetry::layer` to `tracing_subscriber::registry` breaks span exporting to Jaeger

### ISSUE THREAD

**Issue by landonxjames** [tokio-rs/tracing-opentelemetry#159]
### Version

```
$ cargo tree | grep tracing
├── opentelemetry-appender-tracing v0.5.0
│   ├── tracing v0.1.40
│   │   ├── tracing-attributes v0.1.27 (proc-macro)
│   │   └── tracing-core v0.1.32
│   ├── tracing-core v0.1.32 (*)
│   └── tracing-subscriber v0.3.18
│       ├── tracing v0.1.40 (*)
│       └── tracing-core v0.1.32 (*)
│   │       │   │   └── tracing v0.1.40 (*)
│   │       │   └── tracing v0.1.40 (*)
│   │       │   │   └── tracing v0.1.40 (*)
│   │       └── tracing v0.1.40 (*)
├── tracing v0.1.40 (*)
├── tracing-core v0.1.32 (*)
├── tracing-opentelemetry v0.25.0
│   ├── tracing v0.1.40 (*)
│   ├── tracing-core v0.1.32 (*)
│   ├── tracing-log v0.2.0
│   │   └── tracing-core v0.1.32 (*)
│   └── tracing-subscriber v0.3.18 (*)
└── tracing-subscriber v0.3.18 (*)
```

### Platform

```
$ uname -a
Darwin bcd0746352ef 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

### Description

When I add a `tracing_opentelemetry::layer()` to a `tracing_subscriber::registry()` my existing exports to Jaeger breaks. 

To replicate first run the following to start an instance of Jaeger:
```
docker run -d --name jaeger -e COLLECTOR_OTLP_ENABLED=true -p 16686:16686 -p 4317:4317 -p 4318:4318 jaegertracing/all-in-one:latest
```

Then run the following code with the below Cargo.toml:
```toml
[package]
name = "otel-test"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.13"
opentelemetry = { version = "0.24.0", features = ["metrics", "logs"] }
opentelemetry_sdk = { version = "0.24.1", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { version = "0.17.0", features = ["tonic", "metrics", "logs"] }
opentelemetry-semantic-conventions = "0.16.0"
tokio = { version = "1.0", features = ["full"] }
opentelemetry-appender-tracing = { version = "0.5.0", default-features = false}
tracing = { version = "0.1.40", default-features = false, features = ["std"]}
tracing-core = { version = "0.1.32", default-features = false}
tracing-subscriber = { version= "0.3.18", default-features = false, features = ["env-filter","registry", "std"] }
tracing-opentelemetry = "0.25.0"

```

```rust
use opentelemetry::global::shutdown_tracer_provider;
use opentelemetry::{
    global,
    trace::{TraceContextExt, TraceError, Tracer, TracerProvider},
    KeyValue,
};
use opentelemetry_otlp::WithExportConfig;
use opentelemetry_sdk::{runtime, trace as sdktrace, Resource};
use opentelemetry_semantic_conventions::resource::SERVICE_NAME;
use tracing_subscriber::prelude::*;

use std::error::Error;

fn init_tracer_provider() -> Result<opentelemetry_sdk::trace::TracerProvider, TraceError> {
    opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("http://localhost:4317"),
        )
        .with_trace_config(
            sdktrace::Config::default()
                .with_resource(Resource::new(vec![KeyValue::new(SERVICE_NAME, "BLAHBLAH")])),
        )
        .install_batch(runtime::Tokio)
}

#[tracing::instrument()]
fn do_the_thing(num: u8) {
    tracing::info!("I AM DOING THE THING {num}");
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    let tracer_provider = init_tracer_provider().expect("Failed to initialize tracer provider.");
    let foo_tracer = tracer_provider.tracer("FOO_TEST");
    global::set_tracer_provider(tracer_provider.clone());

    let tracer = global::tracer("tracing-jaeger");

    // Uncommenting the lines below will break trace exporting to Jaeger
    // let telemetry_layer = tracing_opentelemetry::layer().with_tracer(foo_tracer);
    // tracing_subscriber::registry().with(telemetry_layer).init();

    tracer.in_span("main-operation", |cx| {
        let span = cx.span();
        span.set_attribute(KeyValue::new("my-attribute", "my-value"));
        span.add_event(
            "Main span event".to_string(),
            vec![KeyValue::new("foo", "1")],
        );
        tracer.in_span("child-operation...", |cx| {
            let span = cx.span();
            span.add_event("Sub span event", vec![KeyValue::new("bar", "1")]);
        });
    });

    do_the_thing(1);

    shutdown_tracer_provider();
    Ok(())
}
```

Running the above as is will export the traces created by the OTel crates to Jaeger. Uncommenting the below lines will cause that exporting to fail:
```rust
    // let telemetry_layer = tracing_opentelemetry::layer().with_tracer(foo_tracer);
    // tracing_subscriber::registry().with(telemetry_layer).init();
```

Instead I would have expected these lines to export the spans created by the `tracing` crate to Jaeger alongside the spans created by the Otel crates. Initially [reported this to the OTtel crates](https://github.com/open-telemetry/opentelemetry-rust/issues/1962), but seems like it is likely coming from `tracing_opentelemetry`.
