### ISSUE TITLE
`OpenTelemetry trace error occurred.` when call `SubscriberInitExt::set_default` in tokio blocking thread.

### ISSUE THREAD

**Issue by xuxiaocheng0201** [tokio-rs/tracing-opentelemetry#161]
### Version
```toml
anyhow = "^1.0"
tokio = { version = "^1", features = ["rt-multi-thread", "macros"]}
tracing = "~0.1"
tracing-subscriber = "~0.3"
tracing-opentelemetry = "~0.25"
opentelemetry = "~0.24"
opentelemetry_sdk = { version = "~0.24", features = ["rt-tokio"] }
opentelemetry-otlp = "~0.17"
```
```text
│   │       │   │   └── tracing v0.1.40
│   │       │   │       ├── tracing-attributes v0.1.27 (proc-macro)
│   │       │   │       └── tracing-core v0.1.32
│   │       │   └── tracing v0.1.40 (*)
│   │       │   │   └── tracing v0.1.40 (*)
│   │       └── tracing v0.1.40 (*)
├── tracing v0.1.40 (*)
├── tracing-opentelemetry v0.25.0
│   ├── tracing v0.1.40 (*)
│   ├── tracing-core v0.1.32 (*)
│   ├── tracing-log v0.2.0
│   │   └── tracing-core v0.1.32 (*)
│   └── tracing-subscriber v0.3.18
│       ├── tracing-core v0.1.32 (*)
│       └── tracing-log v0.2.0 (*)
└── tracing-subscriber v0.3.18 (*)
```

### Platform
```text
Darwin xuxiaocheng 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
```

### Description
I made a minimal example:
```rust
use anyhow::Result;
use opentelemetry::trace::TracerProvider;
use tracing::dispatcher::DefaultGuard;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::registry;
use tracing_subscriber::util::SubscriberInitExt;

fn set_tracing() -> Result<DefaultGuard> {
    let tracer = opentelemetry_otlp::new_pipeline().tracing()
        .with_exporter(opentelemetry_otlp::new_exporter().tonic())
        .with_trace_config(opentelemetry_sdk::trace::Config::default().with_resource(opentelemetry_sdk::Resource::new([
            opentelemetry::KeyValue::new("service.name", "example")
        ])))
        .install_batch(opentelemetry_sdk::runtime::Tokio)?
        .tracer("otlp_tracer");
    let otlp = tracing_opentelemetry::layer().with_tracer(tracer);
    Ok(registry().with(otlp).set_default())
}

#[tokio::main]
async fn main() -> Result<()> {
    let guard = tokio::task::spawn_blocking(|| set_tracing()).await??;

    #[tracing::instrument]
    async fn log() {
        tracing::info!("Log something");
    }
    log().await;

    drop(guard);
    Ok(())
}
```
It prints `OpenTelemetry trace error occurred. cannot send message to batch processor as the channel is closed` on stderr, and no event is sent out.
If I replace `let guard = tokio::task::spawn_blocking(|| set_tracing()).await??;` with `let guard = set_tracing()?;`, all things will work.
If I replace `Ok(registry().with(otlp).set_default())` with `Ok(registry().with(otlp).init())` (and replace the return type, etc.), the error message won't be printed, but still no event be sent out.
