### ISSUE TITLE
tracing_opentelemetry with otlp and tonic hangs forever with with_simple_exporter

### ISSUE THREAD

**Issue by jaysonsantos** [tokio-rs/tracing-opentelemetry#204]
## Bug Report

When using tracing opentelemetry with otlp and tonic and simple exporter (on tests), after test is done, it will hang foverever.

### Version

cargo tree|grep tracing
│   └── tracing v0.1.41
│       ├── tracing-attributes v0.1.28 (proc-macro)
│       └── tracing-core v0.1.33
│   │   │   │   │   └── tracing v0.1.41 (*)
│   │   │   │   └── tracing v0.1.41 (*)
│   │   └── tracing v0.1.41 (*)
│   │   │   └── tracing v0.1.41 (*)
│   │       │   └── tracing v0.1.41 (*)
│   │       └── tracing v0.1.41 (*)
│   └── tracing v0.1.41 (*)
├── tracing v0.1.41 (*)
├── tracing-opentelemetry v0.30.0
│   ├── tracing v0.1.41 (*)
│   ├── tracing-core v0.1.33 (*)
│   ├── tracing-log v0.2.0
│   │   └── tracing-core v0.1.33 (*)
│   └── tracing-subscriber v0.3.19
│       ├── tracing-core v0.1.33 (*)
│       └── tracing-log v0.2.0 (*)
└── tracing-subscriber v0.3.19 (*)
### Platform

 uname -a
Linux desktop-home 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux

### Description

This can be reproduced with the following:

Cargo.toml

```toml
[package]
name = "otel-sdk-bug-report"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = "0.29.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
opentelemetry_api = "0.20.0"
opentelemetry_sdk = "0.29.0"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = "0.3.19"

```

src/main.rs

```rust
use opentelemetry::trace::TracerProvider;
use opentelemetry_otlp::{SpanExporter, WithExportConfig};
use opentelemetry_sdk::trace;
use std::{sync, time::Duration};
use tokio::time::sleep;
use tracing::instrument;
use tracing_subscriber::prelude::*;

static INIT: sync::Once = sync::Once::new();

pub fn init_goodies() {
    INIT.call_once(|| {
        let span_exporter = SpanExporter::builder()
            .with_http()
            .with_timeout(Duration::from_secs(2))
            .build()
            .unwrap();

        let tracer_provider = trace::SdkTracerProvider::builder()
            .with_simple_exporter(span_exporter)
            .build();

        let otel_layer = tracing_opentelemetry::layer()
            .with_tracer(tracer_provider.tracer("testing"))
            .with_error_fields_to_exceptions(true)
            .with_error_records_to_exceptions(true);
        tracing_subscriber::registry().with(otel_layer).init();
    })
}

#[instrument]
async fn t() {
    sleep(Duration::from_secs(1)).await;
}

#[tokio::test]
async fn my_test() {
    init_goodies();
    t().await;
}

fn main() {}
```

and then run `cargo test` and it will hang forever.
i also tested `with_batch_exporter` and that finishes ok, but i did not get to the point of checking the spans are really there
